version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: auction-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auctionDB
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-data:
